"""initial schema

Revision ID: 8696a72fef7b
Revises: 
Create Date: 2026-10-06 15:46:19.363014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8696a72fef7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autonomy_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('promoted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'action_class')
    )
    op.create_index(op.f('ix_autonomy_state_action_class'), 'autonomy_state', ['action_class'], unique=False)
    op.create_index(op.f('ix_autonomy_state_agent_id'), 'autonomy_state', ['agent_id'], unique=False)
    op.create_table('consumed_tokens',
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_index(op.f('ix_consumed_tokens_decision_id'), 'consumed_tokens', ['decision_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rules_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('deactivated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.CheckConstraint('(is_active AND activated_at IS NOT NULL AND deactivated_at IS NULL) OR (NOT is_active AND ((activated_at IS NULL AND deactivated_at IS NULL) OR (activated_at IS NULL AND deactivated_at IS NOT NULL)))', name='ck_policies_activation_invariant'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_is_shadow'), 'policies', ['is_shadow'], unique=False)
    op.create_index(op.f('ix_policies_policy_hash'), 'policies', ['policy_hash'], unique=True)
    op.create_index(op.f('ix_policies_version'), 'policies', ['version'], unique=False)
    op.create_index('uq_policies_one_active', 'policies', ['is_active'], unique=True, postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.create_index('uq_policies_one_shadow', 'policies', ['is_shadow'], unique=True, postgresql_where=sa.text('is_shadow'), sqlite_where=sa.text('is_shadow'))
    op.create_table('decision_records',
    sa.Column('decision_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('autonomy_level', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('policy_hash', sa.String(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('capability_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_hash'], ['policies.policy_hash'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_decision_records_agent_id'), 'decision_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_decision_records_policy_hash'), 'decision_records', ['policy_hash'], unique=False)
    op.create_index(op.f('ix_decision_records_request_id'), 'decision_records', ['request_id'], unique=True)
    op.create_table('escalation_queue',
    sa.Column('escalation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('package_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_records.decision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('escalation_id')
    )
    op.create_index(op.f('ix_escalation_queue_decision_id'), 'escalation_queue', ['decision_id'], unique=False)
    op.create_index(op.f('ix_escalation_queue_status'), 'escalation_queue', ['status'], unique=False)
    op.create_table('shadow_records',
    sa.Column('shadow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('candidate_policy_hash', sa.String(), nullable=False),
    sa.Column('would_have_decided', sa.String(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_policy_hash'], ['policies.policy_hash'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_records.decision_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('shadow_id')
    )
    op.create_index(op.f('ix_shadow_records_candidate_policy_hash'), 'shadow_records', ['candidate_policy_hash'], unique=False)
    op.create_index(op.f('ix_shadow_records_decision_id'), 'shadow_records', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_records_decision_id'), table_name='shadow_records')
    op.drop_index(op.f('ix_shadow_records_candidate_policy_hash'), table_name='shadow_records')
    op.drop_table('shadow_records')
    op.drop_index(op.f('ix_escalation_queue_status'), table_name='escalation_queue')
    op.drop_index(op.f('ix_escalation_queue_decision_id'), table_name='escalation_queue')
    op.drop_table('escalation_queue')
    op.drop_index(op.f('ix_decision_records_request_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_policy_hash'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_agent_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index('uq_policies_one_shadow', table_name='policies', postgresql_where=sa.text('is_shadow'), sqlite_where=sa.text('is_shadow'))
    op.drop_index('uq_policies_one_active', table_name='policies', postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.drop_index(op.f('ix_policies_version'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_hash'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_shadow'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_consumed_tokens_decision_id'), table_name='consumed_tokens')
    op.drop_table('consumed_tokens')
    op.drop_index(op.f('ix_autonomy_state_agent_id'), table_name='autonomy_state')
    op.drop_index(op.f('ix_autonomy_state_action_class'), table_name='autonomy_state')
    op.drop_table('autonomy_state')
    # ### end Alembic commands ###
